config/routes.rb
FirstApp::Application.routes.draw do

  root to: "static_pages#home"

  get "algorithms/new"

  get "registration_confirmations/new"

  get "registration_confirmation/new"

  get "password_resets/new"

  get "courses/new"
  
  post "users/upload"
  
  get "items/reseed"
  
  get "groups/assign"

  resources :users
  resources :questions
  resources :items
  resources :elements
  resources :courses
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets
  resources :registration_confirmations
  resources :profiles
  resources :tasks
  resources :groups
  resources :feedbacks

  match '/add_element', to: 'elements#add_to_item', via: [:get, :post]
  match '/addquestion', to: 'questions#add_to_item', via: [:get, :post]
  match '/newstage', to: 'courses#add_stage', via: [:get, :post]
  match '/confirm_password', to: 'password_resets#confirm_password', via: [:get, :post]

  match '/signup',  to: 'users#new', via: [:get, :post]
  match '/signin',  to: 'sessions#new', via: [:get, :post]
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/help', to: 'static_pages#help', via: [:get]
  match '/about', to: 'static_pages#about', via: [:get]
  match '/contact', to: 'static_pages#contact', via: [:get]
  match '/courseitem', to: 'profiles#show_item', via: [:get]
  match '/tasks/:id', to: 'tasks#show', via: :post
  match '/elements/update_tags', to: 'elements#update_tags', via: :post

mathjax 'mathjax'
end

app/models/element.rb
# == Schema Information
#
# Table name: elements
#
#  id           :integer         not null, primary key
#  category     :string(255)
#  name         :string(255)
#  content      :text
#  tags         :text
#  created_at   :datetime        not null
#  updated_at   :datetime        not null
#  safe_content :text            default("")
#  author       :integer         default(1)
#

class Element < ActiveRecord::Base
  attr_accessible :content, :name, :tags, :category

  validates :name, presence: true, uniqueness:  { case_sensitive: false }

  validates :category, presence: true, format:{with: /text|video|image/}

  def self.search(search,onlyme,user)
    
    if search&&onlyme
      where('tags LIKE ? AND author = ?', "%#{search}%", user)
    elsif search
      where('tags LIKE ?', "%#{search}%")
    elsif onlyme
      where('id = ?', user)
    else
      scoped
    end
  end
  
end

app/controllers/elements_controller.rb
class ElementsController < ApplicationController

    include ApplicationHelper

	helper_method :sort_column, :sort_direction
    before_filter :author_user
    before_filter :abandon_course_build

    def destroy
        Element.find(params[:id]).destroy
        flash[:success] = "Element destroyed."
        redirect_to elements_path
    end

    def index
        #@elements = Element.paginate(page: params[:page])
        params[:sort]||='id'
        params[:direction]||='desc'

        # @videos=Element.find(:all)
        # @videos.each do |v|
        #     if v[:category]=="video"&&v[:content].match(/\Ahttps:\/\/www\.youtube\.com\/.*\z/)
        #         v.update_attribute(:content,"http"+v[:content][5..-1])
        #     end
        # end



        @elements = Element.search(params[:search],params[:onlyme],current_user.id).order(params[:sort] + ' ' + params[:direction]).paginate(per_page: number_per_page, page: params[:page])
        
    end


    def show
    	@element = Element.find(params[:id])
        session[:new_element_id]= @element.id.to_s
    end

    def edit
        @element = Element.find(params[:id])
    end

    def update
        @element = Element.find(params[:id])
        if @element.update_attributes(params[:element])
            if naughty_content?(@element)
                flash.now[:failure] ="Element update attempted, but "+@flash_text
                @element.update_attribute(:content, "")
                @element.update_attribute(:safe_content, "")
                render "edit"
            else
                flash.now[:success] = "element updated."
                @element.update_attribute(:safe_content, @element.content) 
                redirect_to @element
            end

        end
    end


	def new
        @element = Element.new
    end

    def create
        @element = Element.new(params[:element])
        tags = @element.tags
        if params["htmlstring"] != ""
            oldcode = ""
            t = params["htmlstring"].split("u003c")
            data = []

            t.each do |u|
                v = u.split(/video_id=([^\\]+)/)
                tycode = v[1]
                if tycode and tycode != oldcode
                    oldcode = tycode
                    title = v[2].split('\\')[-1][5..-1]
                    #nam = title
                    link = "https://www.youtube.com/embed/" + tycode + "?rel=0"
                    unless Element.find_by_content(link)
                        # i = 1
                        # until !Element.find_by_name(nam)
                        #     nam = title + "(#{i})"
                        #     i += 1
                        # end
                        data << [uniquify(title,Element),link]
                    end


                end
            end
            data.reverse.each do |nam,link|
                @el = Element.new
                @el.update_attribute(:name , nam)
                @el.update_attribute(:tags , tags)
                @el.update_attribute(:category , "video")
                @el.update_attribute(:content , link)
                @el.update_attribute(:safe_content , link)
                @el.update_attribute(:author, current_user.id) if current_user
                @el.save
            end
            redirect_to action: "index"
        else
            if current_user
                @element.update_attribute(:author, current_user.id)
            end
            if @element.save
                
                if naughty_content?(@element)
                    flash.now[:failure] ="Element created, but "+@flash_text
                    @element.update_attribute(:content, "")
                    @element.update_attribute(:safe_content, "")
                    render "edit"
                else
                    flash.now[:success] = "element created."
                    @element.update_attribute(:safe_content, @element.content) 
                    redirect_to @element
                end
            else
                render 'new'
            end
        end
    end

    def update_tags
        taglist = params[:tags]
        idlist = params[:id]
        n = taglist.count
        n.times do |i|
            id, tag = idlist[i], taglist[i]
            element = Element.find(id)
            element.update_attribute(:tags, tag)
        end
        redirect_to action: "index"
    end

    def add_to_item


        #@element = Element.find(params[:id])
        
        @item=Item.find_by_id(session[:current_item_id])
        @item[:content]=(arrayify_item_content(@item[:content]) << (params[:element]).to_s).to_s
        @item.update_attributes(params[:item])

        flash.now[:success] = "Added Element "+params[:element].to_s+" to Item "+@item.id.to_s
        index
        session[:new_element_id]=nil
        render "index"
    end

    private

    def sort_direction
        %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
    end

    def sort_column
        Element.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end

    def author_user
        if current_user
            redirect_to(root_path) unless current_user.author
        else
            redirect_to(signin_path)
        end
    end

    def naughty_content?(element)
        if element[:category]=="text"
            if element[:content].match(/.*<.*>.*/)
                @flash_text = 'for html safeness please avoid using "< ... >". You can use MathJax \\gt and \\lt. Please resubmit content.'
                true
            else
                false
            end
        elsif element[:category]=="image"
            if element[:content].match(/\Ahttp:\/\/i970\.photobucket\.com\/albums\/.*\.((png)|(jpg)|(gif))\z/)
                false
            else
                @flash_text = "Only png, gif and jpg files with urls starting 'http://i970.photobucket.com/albums' currently allowed. Please resubmit content."
                true
            end
        elsif element[:category]=="video"
            if element[:content].match(/\A(http:\/\/www\.dailymotion\.com\/.*)|((http:|https:)?(\/\/)?(www\.youtube\.com|youtu\.be)\/.*)\z/)
                if element[:content].match(/\A\/\/www\.youtube\.com\/.*\z/)
                    element[:content]="https:"+element[:content]
                end
                if element[:content].match(/\Awww\.youtube\.com\/.*\z/)
                    element[:content]="https://"+element[:content]
                end
                if element[:content].match(/\Ahttp:\/\/www\.youtube\.com\/.*\z/)
                    element[:content]="https"+element[:content][5..-1]
                end
                if element[:content].match(/\Ahttps:\/\/www\.youtube\.com\/.*\z/)
                    unless element[:content].match(/.*?rel=0\z/)
                        element[:content]=element[:content]+"?rel=0"
                    end
                end
                false
            else
                @flash_text = "Only YouTube and DailyMotion videos currently allowed. Please resubmit content."
                true
            end
        else
            true
        end
    end
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/views/elements/_element.html.erb

  <% short ||= false %>
  <tr>
    <td>
	     <%= element.id %>
    </td>
    <td>
  <%= link_to element.name, element %>
  </td>
  <% unless short %>    <td>
  <%= User.find_by_id(element.author) ? User.find_by_id(element.author).name : '' %>
  <% end %>
  </td>
  <td>
  <%= element.category %>
  </td>
  <td>
  <% if short %>
  <%= element.tags %>
  <% else %>
    <i><%= text_field_tag "tags[]", element.tags, class: "small", size: "18" %></i>
    <%= hidden_field_tag "id[]", element.id %> 
      </td>
      <td>
    <%= submit_tag '  update  ', class: "tagbutton" %>
  <% end %>
  </td>
  <% if short and current_user.author?%>
    <td class = "f2"><%= check_box_tag("out"+element.id.to_s,"yes") if @content.match("( |\\A)#{element.id.to_s}( |\\z)")%></td>
    <td class = "f0"><%= check_box_tag("1in"+element.id.to_s,"yes") %></td>
    <td class = "f0"><%= check_box_tag("2in"+element.id.to_s,"yes") %></td>
    <td class = "f0"><%= check_box_tag("3in"+element.id.to_s,"yes") %></td>
    <td><%= f.submit 'Update', class: "tagbutton"  %><%= f.submit 'Finish', class: "tagbutton"  %></td>
    <%=  %>
  <% else %>
    <td> 
    <% if current_user.author? %>

      <%= link_to "edit", edit_element_path(element.id) %>

        <% if session[:current_item_id] %>
       
        | <%= link_to "add to item "+session[:current_item_id].to_s, :controller => "elements", :action => "add_to_item", :element=>element.id, :search=>params[:search], :sort=>params[:sort], :direction=>params[:direction] %>
        
        
        <% end %>
      <% end %>
    <% if current_user.admin?||current_user.id==element.author%>

       | <%= link_to "delete", element, method: :delete,
                                    data: { confirm: "You sure?" } %>

    <% end %>
    </td>
  <% end %>
  
    

  </tr>


app/views/elements/index.html.erb
<% provide(:title, 'Elements Index') %>
<h1>Elements Index</h1>
<%= will_paginate %>

<%= link_to("New Element", new_element_path) %><br><br>
<% if session[:current_item_id] %>
<%= link_to("Go to Item "+session[:current_item_id].to_s, "/items/"+session[:current_item_id].to_s+"/edit") %>
<p>
<% end %>
<%= form_tag elements_path, :method => 'get' do %>
  
  <%=render 'layouts/indexintro' %>

<% end %>
<%= form_tag 'elements/update_tags', multipart: true do%>
	<table class="table" align="left">
	<tr>  
		<th><%= sortable "id" %></th>
		<th><%= sortable "name" %></th> 
		<th><%= sortable "author" %></th>    
		<th><%= sortable "category" %></th>  
		<th><%= sortable "tags" %></th>
		<th> </th>
	</tr>

		<% for element in @elements %>
		    <%= render element %>
		<% end %>



	</table>

<% end %>
<%= link_to("New Element", new_element_path) %>

<%= will_paginate %>


<% if session[:current_item_id] %>
<p>
<%= link_to("Go to Item "+session[:current_item_id].to_s, "/items/"+session[:current_item_id].to_s+"/edit") %>
<% end %>

app/views/elements/new.html.erb
<%= provide(:title, 'New Element') %>
<h1>Enter a New Element</h1>


<div class="row">
  <div class="span6 offset3">
    <%= form_for(@element) do |f| %>
      <%= render 'shared/eerror_messages' %>

      <%= f.label :category, :style => "font-size: 1.7em;"%>  
      <%= f.radio_button :category, "text" %> text 
      <%= f.radio_button :category, "image" %> image
      <%= f.radio_button :category, "video" %> video <br /><br />

      <%= f.label :name, :style => "font-size: 1.7em;"%>
      <%= f.text_field :name %>

      <%= f.label :content, :style => "font-size: 1.7em;"%>
      <%= f.text_area :content, "cols" => 30, "rows" => 5%>

      <%= f.label :tags, :style => "font-size: 1.7em;"%>
      <%= f.text_field :tags %>

      <br>Or you can bulk upload video links by pasting the raw html of the video manager page in Youtube below. The tag will be applied to all.<br>
      <%= text_area_tag "htmlstring"%>


      <%= f.submit "Create Element", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/elements/show.html.erb
<% provide(:title, @element.name) %>

<div class="row">
  <aside class="span10">
    <section>
      <h2> <p>
        Category: <%= @element.category %> <p>
        Name: <%= @element.name %> <p>
        Content: <%= @element.safe_content %> <p>
        <% if @element.category=="image" %>
        	<img src = <%= @element.content %> /> <p>
        <% end %>
        <% if @element.category=="video" %>
			<iframe width="560" height="315" src= <%= @element.content %>  frameborder="0" allowfullscreen></iframe> <p>
        <% end %>
        Tags: <%= @element.tags %> <p>
        <%= link_to("Edit Element", edit_element_path) %><p>
        <%= link_to("New Element", new_element_path) %>
        <% if session[:current_item_id] %>
        <% @item=Item.find_by_id(session[:current_item_id]) %>
        <%= link_to("Add to Item", edit_item_path ) %>
    	<% end %>

      </h2>
    </section>
  </aside>
</div>

app/views/elements/update.html.erb
<% provide(:title, @element.name) %>

<div class="row">
  <aside class="span10">
    <section>
      <h2> <p>
        Category: <%= @element.category %> <p>
        Name: <%= @element.name %> <p>
        <%= @element.content %> <p>
        <% if @element.category=="image" %>
        	<img src = <%= @element.content %> /> <p>
        <% end %>
        <% if @element.category=="video" %>
			<iframe width="560" height="315" src= <%= @element.content %>  frameborder="0" allowfullscreen></iframe> <p>
        <% end %>
        Tags: <%= @element.tags %> <p>
        <%= link_to("Edit Element", edit_element_path) %><p>
        <%= link_to("New Element", new_element_path) %>
        <% if session[:current_item_id] %>
        <% @item=Item.find_by_id(session[:current_item_id]) %>
        <%= link_to("Add to Item", edit_item_path ) %>
    	<% end %>

      </h2>
    </section>
  </aside>
</div>