config/routes.rb
FirstApp::Application.routes.draw do

  root to: "static_pages#home"

  get "algorithms/new"

  get "registration_confirmations/new"

  get "registration_confirmation/new"

  get "password_resets/new"

  get "courses/new"
  
  post "users/upload"
  
  get "items/reseed"
  
  get "groups/assign"

  resources :users
  resources :questions
  resources :items
  resources :elements
  resources :courses
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets
  resources :registration_confirmations
  resources :profiles
  resources :tasks
  resources :groups
  resources :feedbacks

  match '/add_element', to: 'elements#add_to_item', via: [:get, :post]
  match '/addquestion', to: 'questions#add_to_item', via: [:get, :post]
  match '/newstage', to: 'courses#add_stage', via: [:get, :post]
  match '/confirm_password', to: 'password_resets#confirm_password', via: [:get, :post]

  match '/signup',  to: 'users#new', via: [:get, :post]
  match '/signin',  to: 'sessions#new', via: [:get, :post]
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/help', to: 'static_pages#help', via: [:get]
  match '/about', to: 'static_pages#about', via: [:get]
  match '/contact', to: 'static_pages#contact', via: [:get]
  match '/courseitem', to: 'profiles#show_item', via: [:get]
  match '/tasks/:id', to: 'tasks#show', via: :post
  match '/elements/update_tags', to: 'elements#update_tags', via: :post

mathjax 'mathjax'
end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  tags       :text
#  content    :text
#  markpolicy :text
#  created_at :datetime        not null
#  updated_at :datetime        not null
#  author     :integer         default(1)
#

class Item < ActiveRecord::Base

	
	attr_accessible :content, :markpolicy, :name, :tags

	validates :name, presence: true, length: { maximum: 50 },
			uniqueness:  { case_sensitive: false }

  def self.search(search,onlyme,user)
    
    if search&&onlyme
      where('tags LIKE ? AND author = ?', "%#{search}%", user)
    elsif search
      where('tags LIKE ?', "%#{search}%")
    elsif onlyme
      where('id = ?', user)
    else
      where(nil)
    end
  end
  

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    helper_method :sort_column, :sort_direction
    include ApplicationHelper

    before_filter :author_user, only: [:index, :edit, :update, :destroy, :new, :create]
    
    def show 
        if current_user and params[:reseed]
            current_user.reseed
        end
        @item=Item.find(params[:id])
        create_item(@item)
    end

    def destroy
        Item.find(params[:id]).destroy
        flash[:success] = "Item destroyed."
        redirect_to items_path
    end

    def index
        @user=  User.find_by_remember_token(cookies[:remember_token])
        if session[:current_course_id]
            if session[:current_item_id]
                @item=Item.find_by_id(session[:current_item_id])  
                    if @item.update_attributes(params[:item])
                        flash[:success] = "Stopped editing Item "+session[:current_item_id].to_s
                    end
                session[:current_item_id] = nil
            end 

            @course=Course.find_by_id(session[:current_course_id])

            @values=params[:@values]

            @content = eval(@course.content)

            if @values
                @content.each do 
                    |stage|
                    number1=@content.index(stage)
                    (0..2).each do
                        |number2|
                        refstring = number1.to_s+"x"+number2.to_s
                        if @values[refstring]
                            @content[number1][number2]=@values[refstring]
                            @course.content=@content.to_s
                        end
                    end
                end
            end

            @newtag=params[:@newtag]

            if @newtag && @newtag.match(/[^ ]/)
                unless @course.tag.match(" `"+@newtag+"_"+@user.id.to_s+"`")
                    tag=@course.tag+" `"+@newtag+"_"+@user.id.to_s+"`"
                    @course.update_attribute(:tag, tag)
                end
            end

            @oldtag=params[:@oldtag]

            if @oldtag
                string= " `"+@oldtag+"_"+@user.id.to_s+"`"

                    tag=@course.tag.gsub(string,"")
                    @course.update_attribute(:tag, tag)  
            end

            @course_title=params[:@course_title]

            if @course_title
                @course.update_attribute(:name,@course_title )  
            end

            if params[:r]
                @content.delete(["", "", ""])
            end

            if params[:a]
                
                unless @content[-1]==["", "", ""]
                    @content<<["", "", ""]
                    @course.update_attribute(:content, @content.to_s)
                    flash.now[:success] = "Course updated" 
                else
                    flash.now[:failure] = "Put some items in the blank row before adding another - otherwise you'd have two rows the same."
                end
            
            end

            @okness=true
            @content.each do
                |stage|
                stage.each do
                    |item|
                    unless Item.find_by_id(item.to_i)||item==""
                        @okness=false
                    end
                end
            end

            if @okness
      
                @course.update_attribute(:content, @content.to_s)
                flash.now[:success] = "Course updated"
                if params[:f]
                    id=session[:current_course_id]
                    session[:current_course_id]=nil
                    redirect_to course_path(id)
                end
                    
            else
                flash.now[:failure] = "Some of the items specified do not exist"
            end

            #indexitem code nicked from itemscontroller
            #params[:sort]||=''
            #params[:direction]||=''
            #@items = Item.search(params[:search]).order(params[:sort] + ' ' + params[:direction]).paginate(per_page: number_per_page, page: params[:page])


            #render "#"
           
        

        end
        params[:sort]||='id'
        params[:direction]||='desc'
        @items = Item.search(params[:search],params[:onlyme],current_user.id).order(params[:sort] + ' ' + params[:direction]).paginate(per_page: number_per_page, page: params[:page])
    end

    def new
        @item = Item.new
        @item[:content]="[]"
    end

    def create
        session[:new_element_id]=nil
        @item = Item.new(params[:item])
        @item[:content]="[]"
        if current_user
            @item.update_attribute(:author, current_user.id)
        end
        if @item.save
            flash.now[:success] = "Item created."
            session[:current_item_id] = @item.id
            redirect_to @item
        else
            render 'new'
        end
    end

    def edit 
        if session[:current_item_id]&&Item.find_by_id(session[:current_item_id])
            @item=Item.find_by_id(session[:current_item_id])
            if session[:new_element_id]
                @item[:content]=(arrayify_item_content(@item[:content]) << session[:new_element_id]).to_s
                @item.update_attributes(params[:item])
                flash[:success] = "Item updated"
            end
            create_item(@item)
            render "edit"
        
        else
            session[:current_item_id]=params[:id]
            @item=Item.find_by_id(session[:current_item_id])
            create_item(@item)

            render "edit"
       
        end
    end

    def update
        if session[:current_item_id]
            @item=Item.find_by_id(session[:current_item_id])
        else 
            @item=Item.find_by_id(params[:id])
        end

        if @item.update_attributes(params[:item])
            flash[:success] = "Item updated"
            session[:current_item_id] = nil
            redirect_to @item
        else
          #deal with invalid item
        end
    end
 

  private

    def sort_direction
        %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
    end

    def sort_column
        Item.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end

    def author_user
        if current_user
            redirect_to(root_path) unless current_user.author
        else
            redirect_to(signin_path)
        end
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<% provide(:title,  @item.name) %>

<h1>Update Item <%= @item.id %>: <%= @item.name %> </h1>

<div class="row">
  <aside class="span12">
    <section>
       <br>
      	Showing Item <%= @item.id %> <p>

        <%= @item_html.html_safe %>


        Content: <%= @item.content %><%= @content%> <p>
        Name: <%= @item.name %> <p>
        
        Tags: <%= @item.tags %> <p>
        
        <%= link_to "Add a new element", elements_path %><p>

        <%= link_to "Add a new question", questions_path %><p>

      
    </section>
  </aside>
</div>

<div class="row">
  <div class="span10">
  <%= form_for(@item) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :content %>
      <%= f.text_field :content %>
      Example: ["2","4h3h5","Q3", "Q7h6"] means element id 2 followed by element id 4 with elements 3 and 5 under hint buttons, then question id 3 and question id 7 with element id 6 under a hint button"

      <%= f.label :tags %>
      <%= f.text_field :tags %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

  </div>
</div>


app/views/items/index.html.erb


<% if session[:current_course_id] %>

	<% provide(:title, "Course = "+@course.name) %>


	<form>
	<h1>Course: <course><%= @course.name %></course> (editing)</h1>
		<%= render 'shared/cerror_messages' %>
	<table class="table">
	    <tr>  
	        <th>Stage</th>
	        <th>Bronze</th>    
	        <th>Silver</th>  
	        <th>Gold</th>
	    </tr>




	    <% @content.each do %>
	        <%|stage|%>
	        <% stage_number=@content.index(stage) %>

		    <tr><td> <%=stage_number+1%> </td>
	            <td style="vertical-align:middle" width = "100"> <input type="textarea"  name=<%="@values["+stage_number.to_s+"x0]"%> value="<%=stage[0]%>" rows="1" cols="20" ><%= (Item.find_by_id(stage[0])&&Item.find_by_id(stage[0]).name)||(!Item.find_by_id(stage[0])&&"NO SUCH ITEM")%> </td>
	            <td style="vertical-align:middle" width = "100"> <input type="textarea"  name=<%="@values["+stage_number.to_s+"x1]"%> value="<%=stage[1]%>" rows="1" cols="20" ><%= (Item.find_by_id(stage[1])&&Item.find_by_id(stage[1]).name)||(!Item.find_by_id(stage[1])&&"NO SUCH ITEM")%> </td>
	            <td style="vertical-align:middle" width = "100"> <input type="textarea"  name=<%="@values["+stage_number.to_s+"x2]"%> value="<%=stage[2]%>" rows="1" cols="20" ><%= (Item.find_by_id(stage[2])&&Item.find_by_id(stage[2]).name)||(!Item.find_by_id(stage[2])&&"NO SUCH ITEM")%> </td>
		    </tr>
		<% end %>
		    Note: this screen cannot currently cope well if any two rows are identical - you'll notice they get given the same stage number and behaviour after this may not be what you expect. Let Brian know if this is a problem in practice. <br><br>


	</table>

	<br>Course Title <input type="textarea"  name=<%="@course_title"%> value="<%=@course.name%>" rows="1" cols="20">

	
      <h1><p></h1>

	<br>If you are ready to publish this course, add tag here: <input type="textarea"  name=<%="@newtag"%> value="<%=@newtag%>" rows="1" cols="20" > <br>Current tags used for this course are <tag><%= @course.tag %></tag> <br>Remove my tag:<input type="textarea"  name=<%="@oldtag"%> value="<%=@oldtag%>" rows="1" cols="20" > <br> The tag for users will be your string, followed by '_', followed by <%=@user.id.to_s%> (your user id number), e.g. if you enter 'mytag', their tag will be mytag_<%= @user.id.to_s%>  If they enter this in their tags they will see your course<br><br>

	<%= submit_tag "Update", class: "btn btn-medium btn-info",  :name=> "s" %>
	<%= submit_tag "Add Stage", class: "btn btn-medium btn-info",  :name=> "a" %>
	<%= submit_tag "Remove Blank Stages", class: "btn btn-medium btn-info",  :name=> "r" %>
	<%= submit_tag "Finish", class: "btn btn-medium btn-info",  :name=> "f" %>


	</form>
	
	<%= hidden_field_tag :direction, params[:direction] %>
  	<%= hidden_field_tag :sort, params[:sort] %>
  	<%= hidden_field_tag :search, params[:search] %>
<br><h2>Item List</h2>

<% else %>

	<% provide(:title, 'All Items') %>
	<h1>All Items</h1>

<% end %>

<%= link_to("New Item", new_item_path) %><br><br>

<%= will_paginate %>

<%= form_tag items_path, :method => 'get' do %>

	<%=render 'layouts/indexintro' %>

<% end %>

<table class="table" align="left">
<tr>  
	<th><%= sortable "id" %></th>
	<th> <%= sortable "name" %> </th> 
	<th> <%= sortable "author" %> </th>   
	<th> <%= sortable "tags" %> </th>
	<th> </th>
</tr>

	<% for item in @items %>
	<% if item %>
	    <%= render item %>
	<% end %>
	<% end %>



</table>

<%= link_to("New Item", new_item_path) %>

<% if session[:current_item_id] %>
<p>
<%= link_to("Go to Item "+session[:current_item_id].to_s, "/items/"+session[:current_item_id].to_s+"/edit") %>
<% end %>

app/views/items/new.html.erb
/* ONLY ADMINISTRATORS SHOULD HAVE ACCESS */

<%= provide(:title, 'New Item') %>
<h1>Enter a New Item</h1>


<div class="row">
  <div class="span6 offset3">
    <%= form_for(@item) do |f| %>
      <%= render 'shared/ierror_messages' %>

      <%= f.label :name, :style => "font-size: 1.7em;"%>
      <%= f.text_field :name %>

      <%= f.label :tags, :style => "font-size: 1.7em;"%> Keywords that can be used to find this item.
      <%= f.text_field :tags %>

      <%= f.submit "Create Item", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/items/show.html.erb
<% provide(:title, @item.name) %>



<div class="row">
  
    <section>
      <h2> <p>
      <% if params[:really]=="yes" %>
      Course: <course><%= Course.find_by_id(Profile.find_by_id(params[:profile_id]).course).name%></course>
      <br> 
      Item: <%= @item.name %>

      <% else %>  
      	Showing Item <%= @item.id%>:  <%= @item.name %> 

      <% end %>
      
       <%= link_to "Change my numbers!", params.merge({reseed: true}) %>

      </h2>

        <%= @item_html.html_safe %>

        <%= hidden_field_tag(:really, params[:really]) %>
        <%= hidden_field_tag(:profile_id, params[:profile_id]) %> 


      <h2>

      <% if params[:really]=="yes" %>
        <%= link_to "Return to course profile page", :controller => "profiles", :action =>"show", :user_id => Profile.find_by_id(params[:profile_id]).user, :course_id => Profile.find_by_id(params[:profile_id]).course %>
      <% else %>
        Content: <%= @item.content %> <p>
        Name: <%= @item.name %> <p>
        
        Tags: <%= @item.tags %> <p>
        
        <%= link_to "Elements index", elements_path %><p>

        <%= link_to "Questions index", questions_path %><p>

        <%= link_to "Edit this item", edit_item_path %>

      <% end %>

      </h2>
    </section>
  
</div>

app/views/items/test.html.erb



<%= form_tag :action => 'update' %>
<input type="textbox" name=":session[:ar[]]">
<input type="textbox" name=":session[:ar[]]">
<input type="textbox" name=":session[:ar[]]">
<input type="textbox" name=":session[:ar[]]">

 <input type="submit" value="Submit" />
 </form>